export const currencies = [
    { code: "EUR", name: "Euro", symbol: "€", flag: "eu" },
    { code: "USD", name: "US Dollar", symbol: "$", flag: "us" },
    { code: "JPY", name: "Japanese Yen", symbol: "¥", flag: "jp" },
    { code: "BGN", name: "Bulgarian Lev", symbol: "лв", flag: "bg" },
    { code: "CZK", name: "Czech Republic Koruna", symbol: "Kč", flag: "cz" },
    { code: "DKK", name: "Danish Krone", symbol: "kr", flag: "dk" },
    { code: "GBP", name: "British Pound Sterling", symbol: "£", flag: "gb" },
    { code: "HUF", name: "Hungarian Forint", symbol: "Ft", flag: "hu" },
    { code: "PLN", name: "Polish Zloty", symbol: "zł", flag: "pl" },
    { code: "RON", name: "Romanian Leu", symbol: "lei", flag: "ro" },
    { code: "SEK", name: "Swedish Krona", symbol: "kr", flag: "se" },
    { code: "CHF", name: "Swiss Franc", symbol: "CHF", flag: "ch" },
    { code: "ISK", name: "Icelandic Króna", symbol: "kr", flag: "is" },
    { code: "NOK", name: "Norwegian Krone", symbol: "kr", flag: "no" },
    { code: "HRK", name: "Croatian Kuna", symbol: "kn", flag: "hr" },
    { code: "RUB", name: "Russian Ruble", symbol: "₽", flag: "ru" },
    { code: "TRY", name: "Turkish Lira", symbol: "₺", flag: "tr" },
    { code: "AUD", name: "Australian Dollar", symbol: "$", flag: "au" },
    { code: "BRL", name: "Brazilian Real", symbol: "R$", flag: "br" },
    { code: "CAD", name: "Canadian Dollar", symbol: "$", flag: "ca" },
    { code: "CNY", name: "Chinese Yuan", symbol: "¥", flag: "cn" },
    { code: "HKD", name: "Hong Kong Dollar", symbol: "$", flag: "hk" },
    { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", flag: "id" },
    { code: "ILS", name: "Israeli New Sheqel", symbol: "₪", flag: "il" },
    { code: "INR", name: "Indian Rupee", symbol: "₹", flag: "in" },
    { code: "KRW", name: "South Korean Won", symbol: "₩", flag: "kr" },
    { code: "MXN", name: "Mexican Peso", symbol: "$", flag: "mx" },
    { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", flag: "my" },
    { code: "NZD", name: "New Zealand Dollar", symbol: "$", flag: "nz" },
    { code: "PHP", name: "Philippine Peso", symbol: "₱", flag: "ph" },
    { code: "SGD", name: "Singapore Dollar", symbol: "$", flag: "sg" },
    { code: "THB", name: "Thai Baht", symbol: "฿", flag: "th" },
    { code: "ZAR", name: "South African Rand", symbol: "R", flag: "za" }
  ];
  